### use balance
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000000",
  "amount": 100
}

### use balance2
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000000",
  "amount": 100
}

### cancel balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId": "00dec55e01f74805b8ae3d07763eed01",
  "accountNumber": "1000000000",
  "amount": 100
}

### query transaction
GET http://localhost:8080/transaction/8c15f28eed694a59a964b021e262df69